# Generated by Django 6.0.4 on 2026-04-23 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                (
                    "upload_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/projects/%Y/%m/%d/",
                        verbose_name="上传文件",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("parsing", "解析中"),
                            ("ready", "就绪"),
                            ("error", "错误"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("nodejs", "Node.js"),
                            ("python", "Python"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("java", "Java"),
                            ("typescript", "TypeScript"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        max_length=50,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "detected_languages",
                    models.JSONField(default=dict, verbose_name="语言分布"),
                ),
                (
                    "detected_frameworks",
                    models.JSONField(default=list, verbose_name="检测到的框架"),
                ),
                (
                    "total_files",
                    models.IntegerField(default=0, verbose_name="文件总数"),
                ),
                (
                    "total_lines",
                    models.IntegerField(default=0, verbose_name="代码行总数"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="解压根目录"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "db_table": "projects_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "language_distribution",
                    models.JSONField(default=dict, verbose_name="语言分布"),
                ),
                (
                    "dependency_list",
                    models.JSONField(default=list, verbose_name="依赖列表"),
                ),
                (
                    "framework_detected",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="检测到的框架"
                    ),
                ),
                (
                    "code_lines",
                    models.IntegerField(default=0, verbose_name="有效代码行"),
                ),
                (
                    "comment_lines",
                    models.IntegerField(default=0, verbose_name="注释行"),
                ),
                ("blank_lines", models.IntegerField(default=0, verbose_name="空行")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目统计",
                "verbose_name_plural": "项目统计",
                "db_table": "projects_projectstats",
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=1024, verbose_name="相对文件路径"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="编程语言"
                    ),
                ),
                ("line_count", models.IntegerField(default=0, verbose_name="代码行数")),
                ("content", models.TextField(blank=True, verbose_name="文件内容")),
                (
                    "is_vendor",
                    models.BooleanField(default=False, verbose_name="第三方代码"),
                ),
                (
                    "is_generated",
                    models.BooleanField(default=False, verbose_name="生成代码"),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目文件",
                "verbose_name_plural": "项目文件",
                "db_table": "projects_projectfile",
                "unique_together": {("project", "file_path")},
            },
        ),
    ]
