# Generated by Django 6.0.4 on 2026-04-23 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("deepseek", "DeepSeek"),
                            ("ollama", "Ollama"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=50,
                        verbose_name="提供商",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="显示名称"),
                ),
                (
                    "_encrypted_api_key",
                    models.CharField(
                        db_column="api_key",
                        max_length=500,
                        verbose_name="API Key(加密)",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="模型名称"),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API 端点"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认配置"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "extra_settings",
                    models.JSONField(default=dict, verbose_name="额外设置"),
                ),
            ],
            options={
                "verbose_name": "AI 配置",
                "verbose_name_plural": "AI 配置",
                "db_table": "ai_aiconfig",
                "ordering": ["-is_default", "created_at"],
            },
        ),
    ]
