# Generated by Django 6.0.4 on 2026-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconfig",
            name="extra_settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="额外设置"),
        ),
    ]
