# Generated by Django 6.0.4 on 2026-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_add_blank_to_extra_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfig",
            name="fallback_enabled",
            field=models.BooleanField(
                default=False,
                help_text="启用后该配置可作为其他配置的降级备用",
                verbose_name="启用降级",
            ),
        ),
        migrations.AddField(
            model_name="aiconfig",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="数值越大优先级越高，降级时按优先级从高到低选择备用配置",
                verbose_name="优先级",
            ),
        ),
    ]
