# Generated by Django 6.0.4 on 2026-04-23 02:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("ai_model", models.CharField(max_length=100, verbose_name="AI 模型")),
                (
                    "ai_provider",
                    models.CharField(max_length=50, verbose_name="AI 提供商"),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="进度",
                    ),
                ),
                (
                    "total_issues",
                    models.IntegerField(default=0, verbose_name="问题总数"),
                ),
                (
                    "critical_count",
                    models.IntegerField(default=0, verbose_name="关键问题数"),
                ),
                (
                    "high_count",
                    models.IntegerField(default=0, verbose_name="高优先级数"),
                ),
                (
                    "medium_count",
                    models.IntegerField(default=0, verbose_name="中优先级数"),
                ),
                (
                    "low_count",
                    models.IntegerField(default=0, verbose_name="低优先级数"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="总体评估")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="失败原因"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "custom_instructions",
                    models.TextField(blank=True, verbose_name="自定义审查指令"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.project",
                        verbose_name="审查的项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码审查",
                "verbose_name_plural": "代码审查",
                "db_table": "reviews_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=1024, verbose_name="文件路径"),
                ),
                (
                    "start_line",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="起始行号",
                    ),
                ),
                (
                    "end_line",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="结束行号",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "关键"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        max_length=20,
                        verbose_name="严重性",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("security", "安全性"),
                            ("correctness", "正确性"),
                            ("performance", "性能"),
                            ("maintainability", "可维护性"),
                            ("type_safety", "类型安全"),
                            ("completeness", "完整性"),
                            ("best_practices", "最佳实践"),
                        ],
                        max_length=30,
                        verbose_name="审查维度",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="问题标题")),
                ("description", models.TextField(verbose_name="问题描述")),
                ("suggestion", models.TextField(blank=True, verbose_name="修复建议")),
                ("code_snippet", models.TextField(blank=True, verbose_name="问题代码")),
                ("fix_snippet", models.TextField(blank=True, verbose_name="修复代码")),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="置信度",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="reviews.review",
                        verbose_name="所属审查",
                    ),
                ),
            ],
            options={
                "verbose_name": "审查问题",
                "verbose_name_plural": "审查问题",
                "db_table": "reviews_reviewissue",
                "ordering": ["file_path", "start_line"],
            },
        ),
    ]
